### PR TITLE
V0.2 Stealth Skirts (VoronDesign#919)

### PR DESCRIPTION
**Pull request by nhchiu**
- Add missing foot accent piece
  The STL of this part was not available but it's different from the stock V0.2 one.
image

- Fix model details.
  Added chamfers to all the overhang at the little bump-ups that anchors into the extrusion slot.
螢幕擷取畫面 2023-04-01 223524
  Fixed some broken fillet faces.
螢幕擷取畫面 2023-04-01 230619

### CODE REVIEW

**Comment by nhchiu** [comment]
The following changes are made:
1. Merged the front skirt pieces into one part in CAD.
  
image

2. Added 0.4mm chamfer to the edges facing the build plate to minimize the effect of elephant foot on all skirt pieces.

image

3. Added some chamfers on the feet to make them consistent.

image

4. Fixed some small overhang over the grids on the rear skirt.

image

**Comment by nhchiu** [comment]
@Maverick-3D When you have time could you take a look into it and see if it's OK to merge into the Voron repo?
Thank you!

**Review by Maverick-3D — APPROVED** [review]
Everything looks good from my end. Thanks for the help!

**Comment by nhchiu** [comment]
Thank you @Maverick-3D .

~~Can you resolve the conflicts then make a pull request to the Voron repo? (I think that's the usual way for making "mod of mod")~~

~~Otherwise I can directly make the pull request from my side if I have your permission.~~

I made another PR #2 so you can merge easily and I will close this one. Sorry for not getting it right the first time.

Thanks for your time.

**Comment by nhchiu** [comment]
Use #2 instead.

**Pull request closed without merging**
